### ISSUE TITLE
How do I use previewer

### ISSUE THREAD

**Issue by xizhengchao** [ForNeVeR/AvaloniaRider#102]
The Avalonia for rider plugin includes a XAML designer which can be used to show a live preview of the XAML as I'am writing it，How do I use preview,I installed the plug-in and it doesn't show up

**Comment by ForNeVeR** [comment]
Hello!

> The Avalonia for rider plugin includes a XAML designer

Well, not actually _the designer_, but merely _the previewer_. You cannot edit anything in it (not like in Windows Forms designer for VS/Rider or WPF designer in VS); just view your window/control as it will be rendered in the app.

> How do I use preview,I installed the plug-in and it doesn't show up

Usually, the previewer should be shown if you open a solution with Avalonia referenced, build the solution, and then open any XAML file. It's hard to miss the previewer; it will be there.

If you have any additional problems, please leave a comment and share the previewer/IDE logs.
