### ISSUE TITLE
Support monitor DPI

### ISSUE THREAD

**Issue by danwalmsley** [ForNeVeR/AvaloniaRider#109]
Plugin always renders at 96dpi even on high dpi displays.

In AvalonStudio I implemented support for this and for Zooming by:

https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio.Languages.Xaml/RemoteWidget.cs#L29-L46

**Comment by rstm-sf** [comment]
Duplicate of https://github.com/ForNeVeR/AvaloniaRider/issues/9

**Comment by ForNeVeR** [comment]
Yes, this is a duplicate.
