### ISSUE TITLE
Add a grid like background that matches light or dark theme of IDE

### ISSUE THREAD

**Issue by danwalmsley** [ForNeVeR/AvaloniaRider#111]
![image](https://user-images.githubusercontent.com/4672627/107641655-c6f24a00-6c6b-11eb-8ebb-c8ce01e63f8f.png)
Similar to how it was implemented on AvalonStudio.

checkerboard effect means, you know that its not part of ui, as a plain colour can confuse user.

**Comment by ForNeVeR** [comment]
Already done, by nobody else but Dan himself. Thanks!
