### ISSUE TITLE
Doesn't work on Rider 2021.1

### ISSUE THREAD

**Issue by dariomingarelli** [ForNeVeR/AvaloniaRider#129]
The plugin doesn't work on Rider 2021.1 (released today, 8th April).
Is not possible to enable the live preview of Avalonia XAML files (.axaml).

**Comment by ForNeVeR** [comment]
Definitely works for me. Could you please check if you have the latest version installed? As of now, the latest one should be 1.0.0.714167006.

**Comment by dariomingarelli** [comment]
I'm not able to install from the .zip, I receive this erro: "Plugin 'AvaloniaRider' (version '1.0.0.714167006') is not compatible with the current version of the IDE, because it requires build 211.6801 or newer but the current build is RD-211.6693.105".
Instead, from the marketplace I'm able to download only the version 1.0.0.613422352.

**Comment by ForNeVeR** [comment]
Thanks! Something's wrong with the version numbers. I'll release a fix soon.

**Comment by dariomingarelli** [comment]
I'm pleased to help you :-)
