### ISSUE TITLE
Presence of launchSettings.json breaks previewer

### ISSUE THREAD

**Issue by garyttierney** [ForNeVeR/AvaloniaRider#140]
This was an interesting one to debug! The issue starts here: https://github.com/ForNeVeR/AvaloniaRider/blob/master/src/rider/main/kotlin/previewer/MsBuildParameterCollector.kt#L82.

AvaloniaRider attempts to figure out which run configuration (or RunnableProject) to start the previewer with and assumes there'll only be one:

```kotlin
        val runnableProject =
            runnableProjects?.singleOrNull { FileUtil.pathsEqual(it.projectFilePath, runnableProjectFilePath.toString()) }
```

When there's more than one valid runnable project AvaloniaRider bails out and doesn't start the previewer. Usually for me this has been working fine, but a certain `dotnet` command generated a launchSettings.json configuration file and Rider recognizes this as a valid run template, so I started seeing this error in the Rider logs:

```
2021-05-10 04:43:10,123 | WARN  | MsBuildParameterCollector      | Could not find runnable project for path apps\apps.csproj; all runnable projects are apps/apps.csproj, apps/apps.csproj
2021-05-10 04:43:10,123 | WARN  | AvaloniaPreviewerSessionController | Could not find runnable project for path apps\apps
```

I'm not sure what the correct fix is, for me it was easy enough to delete that file to get everything working again. I guess the guard against multiple runnable projects with the same path is there for a reason, so I'm not sure it could just be changed to `firstOrNull`.

**Comment by ForNeVeR** [comment]
Thanks for the detailed investigation! I've already met similar issues in the new assembly selector, and made a quick and dirty attempt to fix them: https://github.com/ForNeVeR/AvaloniaRider/blob/c566c44fa1c99df617caf6ad53cf76a050cb005a/src/rider/main/kotlin/idea/editor/actions/RunnableAssemblySelectorAction.kt#L210-L213

I think a similar fix is required in the `MsBuildParameterCollector`; probably it would be better to share the deduplication logic.
