### ISSUE TITLE
Rider Plugin Update

### ISSUE THREAD

**Issue by furesoft** [ForNeVeR/AvaloniaRider#162]
I cannot install the Rider Plugin because it is not compatible with the current Rider version

**Comment by ForNeVeR** [comment]
Please tell your Rider version, and why do you think it isn't compatible?

**Comment by furesoft** [comment]
![image](https://user-images.githubusercontent.com/4117602/141350679-350fb6dd-3311-4d49-a1b9-5e9b155a03c9.png)
![image](https://user-images.githubusercontent.com/4117602/141350711-fc8b0233-19a4-414f-b16d-1901bb7b19d8.png)

Because Rider say it is incompatible

**Comment by ForNeVeR** [comment]
Sorry, where are you receiving this message? How are you trying to install the plugin? As far as I know, the plugin marketplace should only offer you compatible updates. If you're still on 2021.2, then only 2021.2-compatible versions will be shown. For example, [this one](https://plugins.jetbrains.com/plugin/14839-avaloniarider/versions/dev/130489).
