### ISSUE TITLE
Stuck on StartDesignerSessionMessage, preview is empty

### ISSUE THREAD

**Issue by TETYYS** [ForNeVeR/AvaloniaRider#164]
```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\User\source\repos\App\App\bin\Debug\net6.0\App.runtimeconfig.json --depsfile C:\Users\User\source\repos\App\App\bin\Debug\net6.0\App.deps.json C:\Users\User\.nuget\packages\avalonia\0.10.10\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:7060/ --method avalonia-remote C:\Users\User\source\repos\App\App\bin\Debug\net6.0\App.dll
Obtaining AppBuilder instance from App.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
```

dotnet.exe process is there, preview is empty. How do I view more logs?

Rider 2021.3 EAP 5 #RD-213.5281.17; Avalonia 0.10.10; .NET 6

**Comment by LilPidgey** [comment]
Having the same issue

**Comment by ForNeVeR** [comment]
Do you have a sample project for me to try?

**Comment by TETYYS** [comment]
I have found my mistake while trying to make a minimal reproduction project, `MainWindow` ctor did not have `InitializeComponent();` in it.

@LilPidgey Is your problem also the same?

**Comment by EternalClickbait** [comment]
Facing this issue on the default MMVM project template (no changes)

**Comment by ForNeVeR** [comment]
@EternalClickbait, could you please show the error output from the designer process again, and maybe attach the IDE logs? Are there any error messages anywhere?

**Comment by EternalClickbait** [comment]
Created a test repro project again, only IDE warning was that .Net 6 is not yet fully supported.
Avalonia Designer log is just
```
/usr/share/dotnet/dotnet exec --runtimeconfig /home/rowan/Projects/Test/bin/Debug/net5.0/Test.runtimeconfig.json --depsfile /home/rowan/Projects/Test/bin/Debug/net5.0/Test.deps.json /home/rowan/.nuget/packages/avalonia/0.10.10/buildTransitive/../tools/netcoreapp2.0/designer/Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:34485/ --method avalonia-remote /home/rowan/Projects/Test/bin/Debug/net5.0/Test.dll
Obtaining AppBuilder instance from Test.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
```

![image](https://user-images.githubusercontent.com/48875125/144014376-e96b4e0a-d8fc-4894-bfff-0f8743977b85.png)

[rider-logs-20211130-184401.zip](https://github.com/ForNeVeR/AvaloniaRider/files/7624289/rider-logs-20211130-184401.zip)
*(I did have other projects open so ignore any projects other than "Test")*

**Comment by ForNeVeR** [comment]
@EternalClickbait, here the preview is working. It tells you that the "Application can't be previewed in design view", which is true.

Does it work if you open the `MainWindow.xaml`?

**Comment by EternalClickbait** [comment]
Ah my apologies. It does work when I open the main window. I'm afraid I don't have the original repro and I can't remember what exactly happened :(

**Comment by ForNeVeR** [comment]
Alright, then. If it ever reappears – please post a comment and I'll reopen this.
