### ISSUE TITLE
Error highlighting while using resm resource from NuGet package

### ISSUE THREAD

**Issue by KonH** [ForNeVeR/AvaloniaRider#169]
I made a sample project to show a potential issue with Avalonia support in Rider - https://github.com/KonH/AvaloniaOxyplotIssue.
I am using Oxyplot (https://github.com/oxyplot/oxyplot-avalonia) to add plots in my project and follow instructions from that project readme to import styles:
```
<!-- Add the line below to get OxyPlot UI theme applied. -->
<StyleInclude Source="resm:OxyPlot.Avalonia.Themes.Default.xaml?assembly=OxyPlot.Avalonia"/>
```
Import working (I see a blank window while running if I remove that line), but it is highlighted as invalid in the sample project:

<img width="864" alt="example_invalid" src="https://user-images.githubusercontent.com/2193940/144045059-0ae453ca-8457-45c6-ac55-85c5f8d577ea.png">

But I noticed that the same import is shown as normal inside Oxyplot examples project (https://github.com/oxyplot/oxyplot-avalonia/blob/master/Source/Examples/Avalonia/AvaloniaExamples/App.xaml) but two more shown as invalid:

<img width="920" alt="example_valid" src="https://user-images.githubusercontent.com/2193940/144046099-5f9ea90e-2773-4efc-ab00-67aa414fa490.png">

As I see from the examples project file (https://github.com/oxyplot/oxyplot-avalonia/blob/master/Source/Examples/Avalonia/AvaloniaExamples/AvaloniaExamples.csproj) it depends on the import source:
- Resm resource imported from ProjectReference is shown without issues
- Resm resource imported from PackageReference is shown as invalid

I can make a submodule with the Oxyplot project and import it as ProjectReference but it is less friendly than just import the NuGet package and require additional manual operations to maintain.
I just started to work with Avalonia and it will be great if you could share your knowledge on how this line can be replaced (if it is possible) or maybe that issue is not related to Avalonia support anyway?

**Comment by KonH** [comment]
My setup:
- MacOS Monterey 12.0.1
- .NET 6: 6.0.100-rc.1.21463.6
- Rider 2021.2 + AvaloniaRider 1.0.0.1087501416
- Rider 2021.3 EAP + AvaloniaRider 1.0.0.1456648494

**Comment by ForNeVeR** [comment]
@KonH, thanks for detailed report.

Unfortunately, this plugin doesn't do any code highlighting; it's ReSharper core which does that for us.

So, could you please report it to [the ReSharper issue tracker](https://youtrack.jetbrains.com/issues/RSRP)?

Sorry, I'm closing this here, since it is non-actionable from the plugin side.
