### ISSUE TITLE
Design.PreviewWith for custom controls

### ISSUE THREAD

**Issue by Namek** [ForNeVeR/AvaloniaRider#175]
Hi, is there a way to use `Design.PreviewWith` in a control's XAML?

I know it works when the root of XAML file is the `<Styles>` tag. It shows me then this:
![image](https://user-images.githubusercontent.com/31058/147410185-3c976b1e-901b-49f0-9298-e04f32d4f473.png)
and following the instruction works. 

For any other situation nothing is displayed in the previewer, not even blank white space.

**Comment by ForNeVeR** [comment]
I'm sorry, but this is a question for the Avalonia repository, and not for this plugin. Plugin just uses Avalonia previewer as-is.

If you want to preview styles in some way not supported by the previewer currently, first I'd suggest asking the Avalonia maintainers whether it's possible to actually support that in the previewer itself. And then, if they refuse, it may be a feature request for the plugin. Though, much more detailed specification would be required to implement this, then.
