### ISSUE TITLE
Missing support for Classes conditional binding

### ISSUE THREAD

**Issue by OsaPL** [ForNeVeR/AvaloniaRider#179]
https://github.com/AvaloniaUI/Avalonia/pull/5710

```xml
<Button Classes="Outline"
        Classes.Light="{Binding !IsSelected}"
        Classes.Accent="{Binding IsSelected}"/>
```
Is a correct way to bind classes to a "virtual" property and is similar to how Triggers with setters work.
You'll get "Cant resolve symbol Light".

**Comment by ForNeVeR** [comment]
AvaloniaRider doesn't do any code or error highlighting, and all of this is actually work of Rider (and actually even of ReSharper engine inside of Rider).

Could you please report this [to ReSharper issue tracker](https://youtrack.jetbrains.com/issues/RSRP)?

**Comment by OsaPL** [comment]
Ok, gotcha, thanks anyways.

**Comment by ForNeVeR** [comment]
Thanks!
