### ISSUE TITLE
Plugin not installable in EAP3

### ISSUE THREAD

**Issue by jvbsl** [ForNeVeR/AvaloniaRider#188]
https://plugins.jetbrains.com/plugins/list?channel=dev&pluginId=14839

The minimum version of the newest build released about 2 hours ago `since-build="221.4743"` but EAP 3 on my computer is `221.4501.83`.

If I downloaded it manually and edited the version number in the jar/META-INF/plugin.xml I could install it from the local zip file.

I don't exactly get where the idea-version tag gets added to this file:
https://github.com/ForNeVeR/AvaloniaRider/blob/net221/src/rider/main/resources/META-INF/plugin.xml

**Comment by ForNeVeR** [comment]
Ah, unfortunately, something bad is happening with the Rider SDK, and so I can only build against Nightly SDK (which is not publicly available and is a bit ahead of EAP 3).

I'll try to figure it out.

**Comment by ForNeVeR** [comment]
Wait for a couple of minutes, I believe I've been able to solve this issue.
