### ISSUE TITLE
Build failed on Mac

### ISSUE THREAD

**Issue by rakuten** [ForNeVeR/AvaloniaRider#19]
> Task :compileDotNet FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDotNet'.
> A problem occurred starting process 'command 'powershell''

**Comment by ForNeVeR** [comment]
Yeah, that's true, we don't support build of the backend parts on Mac right now.

I believe that a fully cross-platform build should be possible, and will take a look. Thanks for reporting!
