### ISSUE TITLE
no plugins found

### ISSUE THREAD

**Issue by coolqingcheng** [ForNeVeR/AvaloniaRider#207]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/37170330/170832022-55840e43-c5e5-4013-9a44-b6f4bdc05afd.png">

**Comment by ForNeVeR** [comment]
Which version of Rider do you use?

**Comment by coolqingcheng** [comment]
Rider 2022.2 EAP 1. 

The operating system is MAC OS

**Comment by ForNeVeR** [comment]
Alright, I see. There are no (yet) the plugin verions compatible with 2022.2 EAP. Let me see how to open the EAP program here…

**Comment by ForNeVeR** [comment]
Closed by #208.
