### ISSUE TITLE
Warn if Binding source has an incompatible type

### ISSUE THREAD

**Issue by colejohnson66** [ForNeVeR/AvaloniaRider#214]
Currently, the only way to do typechecking is to use `<Design.DataContext>` or `CompiledBindings`. The former will tell you if your source paths *exist*, but will do no typechecking. The latter *will* do typechecking, but only at compile time. It would be nice to have typechecking at design time as well.

Basically, prevent this:

```cs
using System.Drawing; // note the namespace

public FontFamily MyFontFamily { ... }
```
```xaml
<TextBlock FontFamily="{Binding MyFontFamily}" ... />
```

This code is something that happened yesterday because of autocomplete and me not reading the context hint to add a "using". (I blindly typed "enter" on the first suggestion).

It will compile and run just fine, but the types are incorrect, so any calls to the setter of `MyFontFamily` cause the `<TextBlock>`'s `FontFamily` to be reset to "(unset)". It's a PEBKAC, sure, but if Rider (technically this plugin) had warned me about incompatible types, I would've noticed sooner.

**Comment by colejohnson66** [comment]
`CompiledBindings` don't warn, either:

![Binding `FontFamily` to `MyFontFamily` using a compiled binding](https://user-images.githubusercontent.com/11381599/175318540-8953ab3f-f833-4c6f-89e3-32c1e5eaaca1.png)

In fact, that even compiles!

**Comment by ForNeVeR** [comment]
This plugin currently doesn't do any XAML processing or error highlighting, so I believe that it better stay in the Rider issue tracker, since Rider does all these things. Thanks!
