### ISSUE TITLE
Allow creating Views from Rider (Add -> New...)

### ISSUE THREAD

**Issue by matronator** [ForNeVeR/AvaloniaRider#218]
I looked everywhere but couldn't find an option to create a View file (`view.axaml` and `view.axaml.cs`) from Rider's context menu. I managed to configure a File Template to create a new `.axaml` file with some basic boilerplate, but it doesn't include the `.cs` file inside and can't seem to find a way to do it other than with CLI.

There is a [guide](https://docs.avaloniaui.net/tutorials/todo-list-app/creating-a-view) on how to do it in Visual Studio, but none for Rider, so I'm guessing it's not yet possible?

**Comment by TheM1Stery** [comment]
It's there. It's called **Avalonia User Control**.

**Comment by matronator** [comment]
Oops, sorry, I don't know how that happened, but somehow the plugin got disabled so that's why I wasn't seeing them. Sorry for that 😅
