### ISSUE TITLE
xaml error on casting object in CompiledBinding

### ISSUE THREAD

**Issue by Tenjim** [ForNeVeR/AvaloniaRider#223]
Hi guys,

Just to notify an xaml error when we need to cast an object in a compiled binding like this : 
`DataContext="{Binding (ctrl:ViewModelLocator).MainWindowViewModel, Source={StaticResource ViewModelLocator}}`

I have done a repo to reproduce this issue on Rider:

[repo](https://github.com/Tenjim/AvaloniaSampleCompiledBinding)

Thanks in advance.

**Comment by ForNeVeR** [comment]
Unfortunately, this plugin doesn't do anything about the code/error highlighting. Please report this to ReSharper (since it's the ReSharper engine that does it in Rider): https://youtrack.jetbrains.com/issues/RSRP
