### ISSUE TITLE
Previewer Not Showing Up in Rider

### ISSUE THREAD

**Issue by aridinstitute** [ForNeVeR/AvaloniaRider#234]
I've installed the Avalonia Rider plugin as directed on the documentation, but I'm unable to find the plugin inside a project. The plugins list it as installed, but there's no menu option for it. I'm on the latest versions of both Rider and the plugin.
<img width="575" alt="plugins menu" src="https://user-images.githubusercontent.com/116775947/198174674-929a3e78-468c-479c-8e9e-039fe57f76ac.png">
<img width="310" alt="project menu" src="https://user-images.githubusercontent.com/116775947/198174676-08a53a0b-5d64-478f-80e1-d243e8c6ba79.png">

**Comment by ForNeVeR** [comment]
The plugin doesn't add any menu options. What features are you looking for?

The preview is supposed to enable automatically if you open a XAML file in the editor.

**Comment by DmitriyYukhanov** [comment]
Hey, I don't see a preview too.

Not sure if it's related, but I see "Preview isn't supported for this project" at the preview:

![image](https://user-images.githubusercontent.com/883587/198991219-ee354998-8c42-49cb-82a6-84b48da350eb.png)

Rider 2022.2.3
AvaloniaRider 1.0.0.2140933520
Win 11 22H2

It works fine in Visual Studio 2022 tho.

**Comment by ForNeVeR** [comment]
@DmitriyYukhanov, is it only specific to your project, or will it reproduce for you on a fresh project from a [template](https://github.com/AvaloniaUI/avalonia-dotnet-templates)?

**Comment by DmitriyYukhanov** [comment]
Same with Rider 2022.3 EAP 6 and Avalonia 1.0.0.2140933523

**Comment by ForNeVeR** [comment]
Could you please show the plugin settings page, to double-check that the plugin is installed and enabled? I have tried that with Rider 2022.3 EAP 6, and it works for me :(

**Comment by DmitriyYukhanov** [comment]
@ForNeVeR when I opened settings, it turned out plugin is deactivated, silly me 🙈

So, it works perfectly fine for me, just needed to activate it after installation which I didn't do since I expected it's already active once I install it 😅

Sorry for the false alarm, and thanks for your effort!

**Comment by ForNeVeR** [comment]
Usually, you don't need to manually activate the plugin after installation or update. There has to be some reason for it being disabled.

One possible reason is that it could've thrown an exception on IDE startup earlier (perhaps even a long ago), and was auto-disabled.

**Comment by aridinstitute** [comment]
That worked for me as well!
