### ISSUE TITLE
Text doesn't show when using ScaleTransform with scale below 1

### ISSUE THREAD

**Issue by DmitriyYukhanov** [ForNeVeR/AvaloniaRider#236]
Hey,

I've noticed the following problem: text doesn't show if I use LayoutTransformControl with scale below 1 while rendering text in a Grid column.

Here is a XAML example:

```
<LayoutTransformControl>
	<LayoutTransformControl.LayoutTransform>
		<ScaleTransform ScaleX="1"
		                ScaleY="1">
		</ScaleTransform>
	</LayoutTransformControl.LayoutTransform>
	
	<Grid Name="Content" 
	      RowDefinitions="180,*">
		<Grid Name="ContentHeader"
		      ColumnDefinitions="268,*,Auto"
		      Grid.Row="0"
		      Background="Yellow"
		      ShowGridLines="True">
			<Panel Name="Logo"
			       Grid.Column="0">
			</Panel>
			<Panel Name="SearchBar"
			       HorizontalAlignment="Stretch"
			       VerticalAlignment="Stretch"
			       Grid.Column="1">
			</Panel>
			<StackPanel Name="MenuBar"
			            Grid.Column="2"
			            Orientation="Horizontal"
			            VerticalAlignment="Center"
			            HorizontalAlignment="Right">

				<TextBlock Text="Test"/>
				<TextBlock Text="Test2"/>
			</StackPanel>
		</Grid>
	</Grid>
</LayoutTransformControl>
```

This one renders fine:
![image](https://user-images.githubusercontent.com/883587/199739052-73179d20-53da-4d77-bf5f-e0383c6f1e23.png)

But if I change scale value to 0.5 it stops rendering text:
```
<ScaleTransform ScaleX="0.5"
                ScaleY="0.5">
</ScaleTransform>
```
![image](https://user-images.githubusercontent.com/883587/199739472-233893f5-d0f5-4943-8b0f-0d4c68a7cd93.png)

In the app itself, text is still visible and renders correctly:
![image](https://user-images.githubusercontent.com/883587/199739720-65b9326d-7a93-43cf-81b2-b16a0a80463a.png)

Scale > 1 works fine, problem persists only when using scale below 1.

Rider 2022.2.3
AvaloniaRider 1.0.0.2140933520
Win 11 22H2
Windows Ui Scaling set to 125%
Display resolution 2560 x 1440

I've noticed latest VS 2022 Avalonia plugin version has the very same problem.

**Comment by ForNeVeR** [comment]
Could you try changing the previewer method to HTML and see if that helps?
<img width="737" alt="image" src="https://user-images.githubusercontent.com/92793/199833814-dc1ce6ce-fffc-4b11-a07f-f9da4d9db6a9.png">

**Comment by DmitriyYukhanov** [comment]
Tried this but it doesn't work for me at all D=

![image](https://user-images.githubusercontent.com/883587/199948920-707cd023-3ad6-40ed-9bc2-7b901cdad5c9.png)

**Comment by ForNeVeR** [comment]
If the same issue reproduces in AvaloniaRider and VS extension, then you better report it to [the Avalonia repository](https://github.com/AvaloniaUI/Avalonia).

AvaloniaVS and AvaloniaRider share the same previewer infrastructure, and the previewer itself is hosted in the main repo.
