### ISSUE TITLE
x:Static Member not visible and highlighted as error when using as object element syntax

### ISSUE THREAD

**Issue by hellozyemlya** [ForNeVeR/AvaloniaRider#253]
This example highlighted ass error in plugin, still app compiled & executed absolutely fine.
```
...
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
...
<x:Static Member="exampleMvvm:ExampleViewModel.Design"/>
```
<img width="554" alt="image" src="https://user-images.githubusercontent.com/53153547/207803334-d77bb715-9e23-460d-8a10-5c0b9cdd4cac.png">

**Comment by ForNeVeR** [comment]
Could you please post this to [the ReSharper issue tracker](https://youtrack.jetbrains.com/issues/RSRP)?

The plugin currently does not do any syntax highlighting, and there are no plans to do so (right now, at least). ReSharper has a good support for Avalonia XAML, and we rely on it.
