### ISSUE TITLE
ItemTemplate Design Context only works for ListBox

### ISSUE THREAD

**Issue by taooceros** [ForNeVeR/AvaloniaRider#261]
For ListBox the datacontext is correctly identified, but for other collections (I only tested ItemRepeater and DataGrid), it will not correctly reflect the content type.

![image](https://user-images.githubusercontent.com/45326534/212528680-47338af6-544b-4e19-9dcf-1127601831e1.png)

![image](https://user-images.githubusercontent.com/45326534/212528675-70f2e199-b5fe-4d6e-93be-14e25b10aeb6.png)

**Comment by ForNeVeR** [comment]
Sadly, the plugin has nothing to do with the editor highlighting. Please open an issue on the ReSharper issue tracker: it is Avalonia-aware and should properly work with its XAML.
