### ISSUE TITLE
The process cannot access the file '....' because it is being used by another process.

### ISSUE THREAD

**Issue by j4587698** [ForNeVeR/AvaloniaRider#264]
If files are used in the viewmodel constructor, when debugging will throw System.IO.IOException.
It looks like this file is occupied by the previewer.
If close the axaml page tab, the program can run normally.
Selecting edit only cannot solve this problem.

**Comment by ForNeVeR** [comment]
Yeah, previewer _starts your program_ in preview mode, so if your components have side effects, then those will be applied.

The only way around that is to either restructure the program to not open files in design mode, or to open files with shared access.

Nothing could be done in the plugin, unfortunately.

**Comment by j4587698** [comment]
Ok, I can use `Design.IsDesignMode`. It works normally. But AvaloniaVs can work normally with out  `Design.IsDesignMode`

**Comment by ForNeVeR** [comment]
Could you please share some steps to reproduce the issue, then? If it works in AvaloniaVS but doesn't in AvaloniaRider, that's quite unexpected.

**Comment by j4587698** [comment]
Yes, I create a repo : https://github.com/j4587698/IDETest
It's only open a db file for litedb.
Open MainWindow.axaml at tab.
 If in rider, it will throw IOException, but it's running in vs.

**Comment by j4587698** [comment]
Sorry, The repo created by vs is private by default. I didn't notice. Now it is public.

**Comment by ForNeVeR** [comment]
Ok, here's how it works.

- AvaloniaVS starts previewer with CWD = solution directory, and so your code reads `MyDb.db` from _the solution directory_ while in preview mode.

  When you start your program in run/debug mode, it runs with CWD = bin directory by default (i.e. `bin\Debug\net6.0`).

  This way, the previewer and the program itself _use different files_, and there's no clash.

- AvasloniaRider starts previewer with exact same CWD as the program itself: both the previewer and the program use same CWD, `bin\Debug\net6.0`. So, they both open the same file, and this prevents your program from working correctly.

**Comment by ForNeVeR** [comment]
I'm thinking of adding a setting for that. I still believe that using the same CWD as run mode is a good idea. But for cases like yours, when the users may want to change that default and use some other directory (say, a solution one or some other).
