### ISSUE TITLE
Selector="Image[(asyncImageLoader|ImageLoader.IsLoading)=True]

### ISSUE THREAD

**Issue by afunc233** [ForNeVeR/AvaloniaRider#268]
I use the [AsyncImageLoader.Avalonia](https://github.com/AvaloniaUtils/AsyncImageLoader.Avalonia) version 3.0.0-avalonia11-preview3
``` C#
public static class ImageLoader
{
    public static readonly AttachedProperty<bool> IsLoadingProperty = AvaloniaProperty.RegisterAttached<Image, bool>("IsLoading", typeof (ImageLoader));

    public static bool GetIsLoading(Image element) => element.GetValue<bool>((StyledProperty<bool>) ImageLoader.IsLoadingProperty);

    private static void SetIsLoading(Image element, bool value) => element.SetValue<bool>((StyledProperty<bool>) ImageLoader.IsLoadingProperty, value);
}
```
the Rider has a tips 
![image](https://user-images.githubusercontent.com/19919631/225824764-fefcd490-6bce-4450-9cab-04c5e302efbc.png)
and the application run well 

if replace | to :  got  `Unable to parse selector: Expected '.', got ':' Line 59, position 54. `

I think this is a bug, maybe I was wrong ?

Rider version : JetBrains Rider 2023.1 EAP 8
AvaloniaRider version : 1.0.3.104

**Comment by ForNeVeR** [comment]
Please open an issue on [the ReSharper issue tracker](https://youtrack.jetbrains.com/issues/RSRP). Code highlighting is done by ReSharper core and not this plugin.
