### ISSUE TITLE
preview breaks with custom markup extension that does not use a clr namespace

### ISSUE THREAD

**Issue by tisis2** [ForNeVeR/AvaloniaRider#269]
when i use my custom attribute with the clr xml namespace the preview works and refreshes correctly. as soon as i use the defined xmlns the preview does not work anymore. see gif
![gif_49](https://user-images.githubusercontent.com/18416393/225843943-01bf4216-90cb-4a8c-8cad-23130ba12e71.gif)

**Comment by ForNeVeR** [comment]
Could you please share a sample of the project for me to reproduce the issue?

**Comment by tisis2** [comment]
[CustomXamlNamespace.zip](https://github.com/ForNeVeR/AvaloniaRider/files/11017728/CustomXamlNamespace.zip)

**Comment by ForNeVeR** [comment]
I have [reported this to upstream](https://github.com/AvaloniaUI/Avalonia/issues/12818).
