### ISSUE TITLE
Support checking bindings via `x:DataType`

### ISSUE THREAD

**Issue by jgcodes2020** [ForNeVeR/AvaloniaRider#271]
This is [officially used](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/ControlCatalog/MainView.xaml) by Avalonia samples (for Avalonia 11), and the XAML parser doesn't understand `DesignInstance`.

**Comment by ForNeVeR** [comment]
Could you please tell me more about the "support"? Is the preview of such bindings work well?

Note that this plugin has nothing to do with the XAML parser at this point. So, if you are only concerned with the invalid XAML highlighting, then please open an issue with a particular example on [the ReSharper issues tracker](https://youtrack.jetbrains.com/issues/RSRP).

**Comment by jgcodes2020** [comment]
This is a ReSharper issue, I may post there.
