### ISSUE TITLE
Previewer terminating in Rider

### ISSUE THREAD

**Issue by 1sudo** [ForNeVeR/AvaloniaRider#280]
Rider build #RD-231.9011.39
Avalonia 0.10.21 and Avalonia Rider plugin 1.0.3
Windows 11 22H2 (OS Build 22621.1265)

https://pastebin.com/yGB1gdi0

I got this error, then tried re-installing the Avalonia packages. 

Originally I just couldn't see the preview, it threw that stack trace, but after re-installing Avalonia packages, the app itself is just a black screen, none of my controls show up now.

**Comment by ForNeVeR** [comment]
Could you please share an example of the app?

**Comment by 1sudo** [comment]
I wish I could have just given you the XAML and ViewModel, but I copied it over into a new project and couldn't reproduce it, so the only thing I know to do is just give you the entire app.

[PacketTool.zip](https://github.com/ForNeVeR/AvaloniaRider/files/11715289/PacketTool.zip)
