### ISSUE TITLE
Project template parameter support

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#281]
Avalonia uses a couple of parameters in its dotnet templates, such as `datatype: "choice"` and `datatype: "bool"`. And the set of parameters (or options for `choice`) may change periodically, each major release or even more often.

For example, see this: https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/daee22f696d6fd1ddebabfb6f27fbe356a193e04/templates/csharp/app-mvvm/.template.config/template.json#L17

These parameters (especially, say, Avalonia version) are pretty useful, and it would be nice to have them in the project creation UI.

We should consider either implementing custom support for those in the plugin, or simply implementing support for them in Rider core.

**Comment by maxkatz6** [comment]
Relevant YouTrack issue for Rider support https://youtrack.jetbrains.com/issue/RIDER-16759/Support-parameters-in-custom-project-templates

**Comment by ForNeVeR** [comment]
Done in Rider core.
