### ISSUE TITLE
Preview image is cropped in some cases

### ISSUE THREAD

**Issue by Takoooooo** [ForNeVeR/AvaloniaRider#285]
When building one of our projects we have noticed that preview image in some cases is cropped.
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/53405089/15602b97-1fe4-40e2-b1d4-e98113f78e2d)
To reproduce clone the https://github.com/AvaloniaUI/FinanceAppMockup
Go to HomePageView,build the project and try to zoom in and zoom out.
You will see something like on the first image or something like that
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/53405089/7efec24d-b287-4def-a95d-ad3bd7b5faf4)

**Comment by ForNeVeR** [comment]
So far, I am unable to reproduce the issue (with the newly released Avalonia 11, I assume?), and the repo you've linked is unavailable to me :(
