### ISSUE TITLE
Templates need some attention

### ISSUE THREAD

**Issue by maxkatz6** [ForNeVeR/AvaloniaRider#286]
As reported in our repository https://github.com/AvaloniaUI/avalonia-dotnet-templates/issues/224 templates should not include InitializeComponent method.

As it seems, Rider templates still have it for UserControl and Window ones:
https://github.com/ForNeVeR/AvaloniaRider/blob/7b47af9c8c20c3e742ca179e45bdcdbcd058917f/src/extensions/settings/fileTemplates.DotSettings#L192

But even better if Rider would just use dotnet templates to create these files. I.e. equivalent of `dotnet new avalonia.usercontrol` and `dotnet new avalonia.window`.

**Comment by ForNeVeR** [comment]
Should it be removed for any Avalonia version or just for v11?

**Comment by Mrxx99** [comment]
Ideally Rider would just support dotnet new item templates, here is a issue for it: https://youtrack.jetbrains.com/issue/RIDER-24197/Support-dotnet-new-item-templates
