### ISSUE TITLE
Select platform solution like in VS

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#289]
When create project wanna select platforms for it.
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/33497292/c436314e-8866-485b-97a7-1ef48b882e21)

**Comment by ForNeVeR** [comment]
Please add more details. What project, Avalonia one? Does it correspond to some of the project options mentioned in #281?

**Comment by ForNeVeR** [comment]
There's no plans to do anything aside from #281 on that topic at the moment.
