### ISSUE TITLE
Weird delay/lag on macOS

### ISSUE THREAD

**Issue by JohnKesko** [ForNeVeR/AvaloniaRider#292]
Everything has been working great until today. 
Now for some reason, everything you write in XAML drags/is laggy/gets a weird delay. The keyboard isn't responding at all for a few seconds.

I remember there were some kind of issue before 1.1 on macOS and something about waiting until Rider got updated to 2023.2.
But since the update, it has been working fine. 
I got 1.1.0.112 version.

How can I troubleshoot it? There must be something on my end causing it?
When I disable the plugin, XAML works fine, there is no lag/weird delay.
Any help appreciated.

**Comment by JohnKesko** [comment]
Nevermind, it was a Nuget package causing it. Closing.

**Comment by ForNeVeR** [comment]
Could you please tell what package it was?

**Comment by JohnKesko** [comment]
[Sharp](https://github.com/TolikPylypchuk/SharpHook)

But the problem was actually not the package after some troubleshooting, it was my implementation 🤦 I didn't unsubscribe to all events and also had dangling threads...

**Comment by ForNeVeR** [comment]
So, a lot of threads were spinning in the system due to a problem in your app, which caused the IDE to become less responsive? It could be. Thanks for explanation.
