### ISSUE TITLE
XAML highlighting and preview do not work at all in a "Shared Project"

### ISSUE THREAD

**Issue by martinflorek** [ForNeVeR/AvaloniaRider#296]
I have a solution that has a "Shared Project" with code that I share between multiple Avalonia apps. If I have axaml files in the "Avalonia projects", the plugin works, but every axaml file in the shared project does not have highlighted syntax (at all, everything is just light gray) and the preview window just says "Preview isn't supported for this project". There are no errors nowhere.

Rider 2023.2.1 with .NET 7 and AvaloniaUI 11.0.4.

Is this a known limit of the plugin and could it be fixed? Maybe this is because the pacakges are installed in the Avalonia apps, and no package can be installed in a "Shared Project"? Thank you.

**Comment by ForNeVeR** [comment]
Please [report this to Rider](https://youtrack.jetbrains.com/issues/RIDER) (either via YouTrack link or via **Help → Report a Bug**). The plugin relies on Rider's XAML dialect detection, and that seems to not work with your project.

An example solution (also posted to the Rider issue tracker) would also help.

**Comment by martinflorek** [comment]
Thanks for the reply. Funnily, in the evening the XAML highlighting started to work, without any change to code, solution or Rider. There was no preview though (even the preview's console couldn't be displayed). And now, I also have the preview, and everything works.

**Comment by martinflorek** [comment]
@ForNeVeR I have found the cause and it is maybe a problem with the plugin. It depends on the "Build action" in Visual Studio as defined in the `.projitems` file in the shared project's folder. We have to use `AvaloniaXAML` for the axaml files (I think this is `Page` in WPF), otherwise `InitializeComponent()` does not work in the window's constructor:

    <?xml version="1.0" encoding="utf-8"?>
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
        <PropertyGroup>
            <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
            <HasSharedItems>true</HasSharedItems>
            <SharedGUID>...</SharedGUID>
        </PropertyGroup>
    ...
        <ItemGroup>
            <AvaloniaXAML Include="$(MSBuildThisFileDirectory)App.axaml" />
            <AvaloniaXAML Include="$(MSBuildThisFileDirectory)Views\MainWindow.axaml" />
        </ItemGroup>
    </Project>

This way, there is no syntax highlighting, nor preview. Changing these to `None`, the syntax highlighting starts working and the preview can also show-up if I compile the project before switching from `AvaloniaXML` to `None`:

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)App.axaml" />
        <None Include="$(MSBuildThisFileDirectory)Views\MainWindow.axaml" />
    </ItemGroup>

But I cannot compile the application anymore, I get an error in the `MainWindow` class `Error CS0103 : The name 'InitializeComponent' does not exist in the current context`.

I will try to make a small solution with this problem later today.

**Comment by ForNeVeR** [comment]
This still doesn't sound as a plugin issue. Please report to Rider.

**Comment by martinflorek** [comment]
Thanks, I have reported this to the Rider team https://youtrack.jetbrains.com/issue/RIDER-99201/Avalonia-plugin-does-not-highlight-XAML-syntax-in-a-Shared-Project

I have also prepared an example repository https://github.com/martinflorek/rider-avalonia-plugin-in-shared-project
