### ISSUE TITLE
Avalonia Project Library preview selects wrong class for preview, causes InvalidOperationException

### ISSUE THREAD

**Issue by finlaybob** [ForNeVeR/AvaloniaRider#301]
I'm not sure this is a plugin issue or not. It does seem that way. 

This code works perfectly fine at runtime but I get exact same problem using the Avalonia Visual Studio plugin.

## issue
When I have a console project, which references and creates an Avalonia UI from another (library) project, the previewer doesn't work in the library project. 

The project's layouts are as follows:
<img alt="image" src="https://github.com/ForNeVeR/AvaloniaRider/assets/2033345/b6920848-a831-4d37-892f-6e74a01cc11b">

When I click on MainWindow.axaml I get the following information:
```log
Obtaining AppBuilder instance from ZZBase.Program
Unhandled exception. System.InvalidOperationException: Unable to create AppBuilder from type "ZZBase.Program". Input type either needs to have BuildAvaloniaApp -> AppBuilder method or inherit Application type.
   at Avalonia.AppBuilder.Configure(Type entryPointType)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline)
   at Avalonia.Designer.HostApp.Program.Main(String[] args)
```
This looks like it is trying to find the method on the `ZZZBase` project, which doesn't have this class, or method (and it shouldn't need to, I don't want to initialise anything there). 

It looks like this:
```cs
namespace ZZZBase;

internal static class BaseProg
{
    public static void Main(string[] args)
    {

        if (args.Contains("--ui"))
        {
            ZZZUi.Program.Run(args);
        }
        else
        {
            Console.WriteLine("Console Mode");

        }
    }
}

```

The library project, still has a `Program.cs` and `Program` static class, and a method called `BuildAvaloniaApp`... it's just that it doesn't seem to be utilising that project for the preview - it's trying to use the other one.

ZZZUi/Program.cs:
```cs
using Avalonia;

namespace ZZZUi;

public static class Program
{
    // Initialization code. Don't use any Avalonia, third-party APIs or any
    // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
    // yet and stuff might break.

    public static void Run(string[] args) => BuildAvaloniaApp()
        .StartWithClassicDesktopLifetime(args);

    // Avalonia configuration, don't remove; also used by visual designer.
    public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .UsePlatformDetect()
            .WithInterFont()
            .LogToTrace();
}

```

To me, it seems like the process for selecting the project or passing the project to the previewer, should be using _the project that the file I'm previewing is part of_, not another something else that references it.

**Comment by ForNeVeR** [comment]
Please tell what project are you using as an entry point. There's a selector in the preview window.

**Comment by ForNeVeR** [comment]
Ok, could you please share a solution where I can reproduce this?

**Comment by ForNeVeR** [comment]
Avalonia Previewer works the following way.
1. It finds a runnable project that references the project containing the selected XAML file.
2. In this project, it finds the `BuildAvaloniaApp` method in the entry point class.
3. Then, it calls the method and does its stuff.

In your case, it can be fixed by adding this to `ZZBase.Program`:
```
    public static AppBuilder BuildAvaloniaApp() => ZZUi.Program.BuildAvaloniaApp();
```

You don't need this method in `ZZUi.Program`, though (or even the class `ZZUi.Program` at all if you don't want that project to be runnable).

I have verified that it works the same in Visual Studio previewer.
