### ISSUE TITLE
Preview not showing

### ISSUE THREAD

**Issue by Neyzv** [ForNeVeR/AvaloniaRider#302]
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/104868380/d0549ee0-d305-4498-84c6-818d2bd8c17c)
I have this error while I have created a middle project to store views who are only used by mobiles platforms...
I can't figure out why this happened.

**Comment by Neyzv** [comment]
If I move the same view inside the base project created by Avalonia it works
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/104868380/2da20935-d9b6-4061-97ca-12f19cc9c3dc)
By the way if I copy the base project created by avalonia and I try to show a preview this produce the same problem as shown before

**Comment by ForNeVeR** [comment]
> By the way if I copy the base project created by avalonia and I try to show a preview this produce the same problem as shown before

Please explain what does this mean. Can you share a solution where this reproduces?

**Comment by Neyzv** [comment]
It's simply when I try to create another project named MyProjectName.Mobile to have a shared project for ios and android, I can't previsualize any views inside it

**Comment by Neyzv** [comment]
And by this I mean I have tried to copy past the base project created by avalonia to check if it comes from a miss configuration, but the same issue appear nothing rendered inside the cloned BaseAvaloniaProject
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/104868380/dda37515-06ae-43e0-a8f3-bf566dd4803c)

**Comment by ForNeVeR** [comment]
I still do not understand what you mean by "copy a project". Could you please attach a sample solution?

**Comment by Neyzv** [comment]
[Test.zip](https://github.com/ForNeVeR/AvaloniaRider/files/13042076/Test.zip)
Look at the project .Shared and .Copy in the solution, preview isn't working

**Comment by Neyzv** [comment]
Maybe it's my bad idk

**Comment by ForNeVeR** [comment]
I have opened the file `Test.Copy/Views/MainView.axaml` in the provided solution, and it seems to work fine for me: the previewer loads it with no problems.
![image](https://github.com/ForNeVeR/AvaloniaRider/assets/92793/a4f9228d-a312-41dd-b5e7-eeda7283aff3)

Am I doing it correct, is it the file that's broken for you?

If so, could you please reproduce the issue and upload the IDE logs (**Help → Collect Logs**)?

**Comment by Neyzv** [comment]
Also look at .Mobile Project

**Comment by ForNeVeR** [comment]
Sadly there is no `.Copy` project in the provided solution.

I have manually added the `.Shared` project into it and built it, but as there's no runnable project referencing it, it's impossible to preview.

In your actual solution, are there runnable projects referencing it? If so, then which ones are this?
