### ISSUE TITLE
Preview not working on .NET 8 RC 2 and AOT

### ISSUE THREAD

**Issue by droyer57** [ForNeVeR/AvaloniaRider#303]
The plugin doesn't seem to work with an Avalonia project using .NET 8 RC 2. However, it works fine when I switch to .NET 7. Is there a way to get the plugin to work with .NET 8 ?

Edit: This problem only occurs when using .NET 8 and with `PublishAot` set to true.

**Comment by ForNeVeR** [comment]
Could you please add some details? What exactly doesn't work? Are there any logs from the previewer process?

**Comment by ForNeVeR** [comment]
I'd guess it's impossible to access methods from AOT'd binary via reflection? Most likely, this is a previewer issue, not a plugin one.

**Comment by droyer57** [comment]
Probably, but it works with AOT enabled and .NET 7.
The previewer isn't the plugin ? I mean there is a previewer integrated in Rider ?

**Comment by ForNeVeR** [comment]
> The previewer isn't the plugin ? I mean there is a previewer integrated in Rider by default ?

The previewer itself is maintained by the Avalonia team, and it's a part of the Avalonia NuGet package.

(Yeah, the Avalonia folks are _that_ awesome.)

**Comment by ForNeVeR** [comment]
So far, I am unable to reproduce the issue. For me, it all works fine. Moreover, `<PublishAot>` seems to only change the behavior of publish and not build. So, adding or removing this property shouldn't affect the build normally (and this is what I see locally).

Could you please share a project that reproduces the issue for you?
