### ISSUE TITLE
Preview crash when using generic VM

### ISSUE THREAD

**Issue by Neyzv** [ForNeVeR/AvaloniaRider#305]
Hi,
I'd like to report another bug, if you try to change a bit the base behavior of the ViewModelBase of the app by adding a generic type which is the view that the ViewModel Manage like this :
`public class ViewModelBase<TControl> : ViewModelBase
{
     public TControl View { get; set; }
...
`
The preview isn't build for it

**Comment by ForNeVeR** [comment]
Please share a project to reproduce the issue.

**Comment by Neyzv** [comment]
Look at ViewModelBase.cs | ViewLocator.cs to understand why I'm implementing this pattern to run it as nearly AOT
[GenericViewModelCrash.zip](https://github.com/ForNeVeR/AvaloniaRider/files/13060965/GenericViewModelCrash.zip)

**Comment by ForNeVeR** [comment]
Moved to upstream: https://github.com/AvaloniaUI/Avalonia/issues/13400.

**Comment by timunie** [comment]
@Neyzv looking at your code I think the previewer doesn't manage to provide a window when it is called from Designer, as the desinger simply has no concept of a Window. If I set the View to `null` in this case it works for me. 

```cs
public ViewModelBase()
{
    View = null;
}
```

> **NOTE**
> I still don't get the use-case tbh. Following the MVVM pattern, your ViewModel normally shouldn't have a reference to the View directly. Instead, I'd use an Interaction given your usage of RxUI. If you need a sample, I can share one with you. 

---

Btw: Using a UserControl as the root view also works. 

```cs
public class MainViewModel : ViewModelBase<UserControl>
{
    public string Greeting => "Welcome to Avalonia!";

    public MainViewModel(UserControl view)
        : base(view) { }
    
    public MainViewModel() {}
}
```

```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:viewModels="clr-namespace:GenericViewModelCrash.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="GenericViewModelCrash.Views.UserControl1">
        <Design.DataContext>
        <!-- This only sets the DataContext for the previewer in an IDE,
             to set the actual DataContext for runtime, set the DataContext property in code (look at App.axaml.cs) -->
        <viewModels:MainViewModel />
    </Design.DataContext>
    Welcome to Avalonia!
</UserControl>
```
