### ISSUE TITLE
x:Static as Tag: Member does not resolve

### ISSUE THREAD

**Issue by tisis2** [ForNeVeR/AvaloniaRider#312]
The axaml editor shows a unable to resolve member error on the member property of the x:static tag. same thing does work with WPF. Avalonia is using the same namespace for x: as far as i can see

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/18416393/b6b0a2ab-9ffa-41f9-82ee-b12539cc90af)

the build is working, so it seems the xaml compiler can handle it

**Comment by ForNeVeR** [comment]
Please [open an issue in ReSharper](https://youtrack.jetbrains.com/issues/RSRP). The plugin doesn't handle the code highlighting, and has no plans to do so.

**Comment by tisis2** [comment]
https://youtrack.jetbrains.com/issue/RIDER-101304/xStatic-Member-Property-appears-unresolved-in-an-Avalonia-.axaml
