### ISSUE TITLE
{x:True} and {x:False} boolean constants not recognized as supported symbols

### ISSUE THREAD

**Issue by JosefNemec** [ForNeVeR/AvaloniaRider#325]
Using plugin version 1.3.0, Rider 2023.3.3, the project is .NET 8 project with Avalonia 11.0.9

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/3874087/45de41b5-f82c-477a-8838-0c9a7eb3ed12)

**Comment by ForNeVeR** [comment]
This plugin doesn't implement any highlighting. Please [report this to ReSharper](https://youtrack.jetbrains.com/issues/RSRP).

**Comment by JosefNemec** [comment]
Reported: https://youtrack.jetbrains.com/issue/RSRP-495916/xTrue-and-xFalse-boolean-constants-not-recognized-as-supported-symbols-in-Avalonia-xaml
