### ISSUE TITLE
Unable to show preview

### ISSUE THREAD

**Issue by fatichar** [ForNeVeR/AvaloniaRider#332]
Os: Windows
Rider version: 2023.3.4
Dotnet version: 8

I am unable to view preview for any axaml file. The preview pane has a dropdown, which shows "Loading...", and is disabled. The "Show log" button is enabled, but doesn't show any logs. 

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/10287054/a7663ad4-9c69-4709-b4a6-f0f336481dad)

**Comment by ForNeVeR** [comment]
Could you please share the IDE logs? **Help → Collect Logs** will prepare the archive.

(Mind it may contain sensitive data, so please check them manually before uploading, or share via https://uploads.jetbrains.com that only JetBrains employees have access to.)
