### ISSUE TITLE
ToolTip doesn't come up with AutoComplete

### ISSUE THREAD

**Issue by begleysm** [ForNeVeR/AvaloniaRider#333]
See GIF below.  `ToolTip` does not appear to be recognized as a valid Property for `<Rectangle />` (or any other Control as far as I can tell) for Auto Complete.  However once "ToolTip" has been written its child Properties do appear to be supported and understood by Auto Complete.
![tooltip_rider](https://github.com/ForNeVeR/AvaloniaRider/assets/1275999/06eb1b59-2de1-4b20-bbb7-ad77804f3fc7)

**Comment by ForNeVeR** [comment]
Please [report to ReSharper](https://youtrack.jetbrains.com/issues/rsrp). This plugin doesn't do highlighting or completion.

**Comment by begleysm** [comment]
@ForNeVeR ReSharper is a Visual Studio plugin right?  This is happening in Rider.  Do you know that ReSharper is the right place to submit this given that the issue is in Rider?  Should it, perhaps, be submitted to [Rider](https://youtrack.jetbrains.com/issues?q=project:%20Rider)?

**Comment by ForNeVeR** [comment]
Yes, I know that ReSharper is _the_ right place to submit this. Source: I fulfill the role of JetBrains Rider tech lead as my daily work 😅 

Technically, ReSharper provides Avalonia-based completion and highlighting for both Visual Studio (when enabled) and Rider.

**Comment by begleysm** [comment]
Can't argue with that! haha

I only asked because when I went to submit it to ReSharper it said "hey make sure you include the version of ReSharper and **Visual Studio** you're using" and so I became uncertain that it was the right spot.

I'll report it to ReSharper.  Thanks!

**Comment by ForNeVeR** [comment]
Meh just ignore that requirement. It'll be fine.

**Comment by begleysm** [comment]
Issue submitted to ReSharper here: https://youtrack.jetbrains.com/issue/RSRP-496394/Avalonia-ToolTip-XAML-Property-doesnt-come-up-with-AutoComplete
