### ISSUE TITLE
Avalonia Previewer requires a locally-runnable project to show the preview

### ISSUE THREAD

**Issue by ErickWei** [ForNeVeR/AvaloniaRider#340]
Environment: m1 mac
All the things are the latest version

I created a class libray project,and referenced those packages:
<img width="246" alt="image" src="https://github.com/ForNeVeR/AvaloniaRider/assets/62826892/78b03edf-ae53-49ea-ade6-4306ab0b7100">

and then created a Avalonia UserControl,
But can't preview. and get the warning info like below show:
<img width="1128" alt="image" src="https://github.com/ForNeVeR/AvaloniaRider/assets/62826892/7714e833-f1e5-42d5-a0b6-ac203819e203">

I dont know what can i do for this problem.

**Comment by ForNeVeR** [comment]
Could you please share the sources of your project?

**Comment by ErickWei** [comment]
Hi @ForNeVeR  Here you are.Thank you very much for your attention to this issue.
[ClassLibrary1.zip](https://github.com/ForNeVeR/AvaloniaRider/files/15382874/ClassLibrary1.zip)

**Comment by ErickWei** [comment]
After i referenced this class libray project[usercontrol] to main project[Avalonia .Net App],problem solved.
I think It seems that standalone class library projects cannot be rendered, probably because no avalonia themes or styles are loaded.

**Comment by ForNeVeR** [comment]
Alright, yeah, this is expected.
> probably because no avalonia themes or styles are loaded.

Not exactly like this, but close: the previewer requires a `BuildApp` method (or something like that) from the executable assembly.
