### ISSUE TITLE
Resources.resx do not updated

### ISSUE THREAD

**Issue by derekhe** [ForNeVeR/AvaloniaRider#361]
Hi, 

I follow the Localization sample in this repo (https://github.com/AvaloniaUI/AvaloniaUI.QuickGuides). But seems in rider Resources.resx doesn't convert into Resources.designer.cs, which triggers build errors.

**Comment by ForNeVeR** [comment]
I am not sure what exactly is supposed to convert `Resources.resx` into `Resources.Designer.cs`, but that's definitely out of scope of the plugin.

There should either be an MSBuild task that does this, or something in the IDE (not this plugin).
