### ISSUE TITLE
Get rid of the Avalonia tool window

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#39]
There's an [Avalonia tool window](https://github.com/ForNeVeR/AvaloniaRider/blob/a71d4a81c7056e48e2bcaef9047b110e976d6dbd/src/rider/main/kotlin/idea/AvaloniaToolWindowManager.kt#L15-L18) that's used to host the logs from the previewer process. I don't think it's of use for ordinary users. Let's drop it, and show the stderr/stdout in the IDE log instead.

**Comment by rstm-sf** [comment]
This is a good idea, otherwise windows are created for each xaml and it is not clear which one it belongs to.

![image](https://user-images.githubusercontent.com/2669927/97784742-78400900-1bc2-11eb-8b11-dde08f3cff95.png)
