### ISSUE TITLE
More performant/smart image rendering

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#40]
Current approach to the image rendering in the BSON renderer is rather suboptimal:
1. We create a new `BufferedImage` instance per each frame
2. Whenever we need to update the image, we use a simple loop over all the received image pixels

This needs to be redesigned with more performant and proper approach. See these pieces of code:
https://github.com/ForNeVeR/AvaloniaRider/blob/d620d4c9ab41ce52f6598dfa90a60ea4d2fb20b9/src/rider/main/kotlin/idea/editor/AvaloniaPreviewEditorComponent.kt#L24-L26
https://github.com/ForNeVeR/AvaloniaRider/blob/d620d4c9ab41ce52f6598dfa90a60ea4d2fb20b9/src/rider/main/kotlin/idea/editor/AvaloniaPreviewEditorComponent.kt#L39-L41
https://github.com/ForNeVeR/AvaloniaRider/blob/d620d4c9ab41ce52f6598dfa90a60ea4d2fb20b9/src/rider/main/kotlin/previewer/Graphics.kt#L9-L16
https://github.com/ForNeVeR/AvaloniaRider/blob/d620d4c9ab41ce52f6598dfa90a60ea4d2fb20b9/src/rider/main/kotlin/previewer/Graphics.kt#L18-L30

**Comment by rstm-sf** [comment]
It might be better to replace the following line
https://github.com/ForNeVeR/AvaloniaRider/blob/b3fb65464f31221850ed875da10daf9501a4cd66/src/rider/main/kotlin/idea/editor/BitmapPreviewEditorComponent.kt#L43
with this?
```kotlin
val image = BufferedImage(frame.width, frame.height, BufferedImage.TYPE_INT_RGB)
```

**Comment by ForNeVeR** [comment]
It essentially does the same, but tries to take JBR HiDPI support into account. So I'd say that no, it doesn't make sense in context of this issue.

**Comment by rstm-sf** [comment]
Just that way I stopped observing the behavior from #66. Also, then the next line is no longer needed?
https://github.com/ForNeVeR/AvaloniaRider/blob/b3fb65464f31221850ed875da10daf9501a4cd66/src/rider/main/kotlin/previewer/Graphics.kt#L20

Or does this line just not work?
https://github.com/ForNeVeR/AvaloniaRider/blob/b3fb65464f31221850ed875da10daf9501a4cd66/src/rider/main/kotlin/previewer/AvaloniaPreviewerSessionController.kt#L150
