### ISSUE TITLE
AvaloniaRider extension locking DLL

### ISSUE THREAD

**Issue by dbchandra23** [ForNeVeR/AvaloniaRider#420]
The extension locks the DLL. This caused an issue when I try to use 'dotnet build' which is required when I try to run 'dotnet ef migrations add <name>'. The build DLL could be copied to the output directory because it is locked by the extension. 

When I disabled the extension, everything works. It will be great to have this fixed, or if there is a specific workflow I can use so I don't have to keep disabling the extension when I try to run a build from the command line.

**Comment by ForNeVeR** [comment]
Yes, it does: to show the previewer, we have to pass it to the previewer process, and it has to lock the DLL file on disk (on Windows, that is). I do not know a way around that.

When you use Rider functions (e.g. build the project in Rider), we temporarily shut down all the active previewers and restart them afterwards.

The plugin has no way of knowing what you do in an external (or embedded one, for that matter) terminal, unfortunately.

Not sure what we can do here.

**Comment by ForNeVeR** [comment]
> if there is a specific workflow I can use so I don't have to keep disabling the extension when I try to run a build from the command line.

Currently, to shut down all the previewer processes, you'll have to shut down all the editors with XAML files. Which, of course, would be quite inconvenient.

I think we can easily add a button for you to temporarily suspend all the previewers. The processes would be terminated, you'd do your things in the terminal and then press the button to bring them back up again.

Would that work?
