### ISSUE TITLE
No Preview for Views Defined in Separate Project

### ISSUE THREAD

**Issue by rfvgyhn** [ForNeVeR/AvaloniaRider#422]
When trying to preview views in a project that isn't the main Avalonia project (e.g. class library), the log shows 

> .deps.json file "path/to/main/project/bin/Debug/net8.0/OtherProject.deps.json" doesn't exist, it might affect previewer stability.
> Process terminated with exit code 137

Is this expected?

I'm currently manually symlinking the file to get it to work. It's not a huge problem, but I have to remember to do this for each project and anytime the bin folder is cleaned/deleted.

**Comment by ForNeVeR** [comment]
This is very strange. Normally I believe it should use the `deps.json` from a runnable project anyway (the one you choose on the toolbar). Could you please share the solution in question?

**Comment by rfvgyhn** [comment]
Well, I'm unable to create a minimal, reproducible example and, unfortunately, I can't share the solution as-is. 

If I can narrow it down at some point, I'll re-open this.
