### ISSUE TITLE
CSS color format is not recognized for Color type

### ISSUE THREAD

**Issue by ranstar74** [ForNeVeR/AvaloniaRider#440]
As title states, analysis false detects css color format on **Color** dependency property. It seems to be recognized correctly only for **IBrush**.
![image](https://github.com/user-attachments/assets/18b53ffb-8822-4a7e-9987-f407f381afaf)

**Comment by ForNeVeR** [comment]
Sorry: this plugin doesn't do any source highlighting. Please [report to ReSharper](https://youtrack.jetbrains.com/issues/rsrp).
