### ISSUE TITLE
Unable to resolve symbol 'InitializeComponent'

### ISSUE THREAD

**Issue by Violet-VE** [ForNeVeR/AvaloniaRider#444]
I switched to 11.2.0-rc1, the axaml.cs file located in other projects says: Unable to resolve symbol 'InitializeComponent'

As shown in the image:
![image](https://github.com/user-attachments/assets/67c9cb06-02a6-4a28-aeef-6fdb850a8663)
But in VS there is no such problem!

**Comment by Violet-VE** [comment]
Just realized that it seems to be a problem in .Net9 ....

**Comment by Violet-VE** [comment]
After much verification on my part, I found that this should be due to Avalonia's InitializeComponentCodeGenerator not being able to generate code ....

**Comment by ForNeVeR** [comment]
The plugin doesn't do anything about code highlighting or the project model, so please report to Rider, to .NET or to the Avalonia repo.
