### ISSUE TITLE
Undoing a change off screen does not scroll to change

### ISSUE THREAD

**Issue by grenaria** [ForNeVeR/AvaloniaRider#445]
When editing an AXAML file, using undo when the last change is off the screen does not scroll to that change. Standard behavior in editors is to scroll to the last change when using undo and only actually undoing the change if it is in view. For the AXAML editor in Rider the change is just undone whether or not it is in view. This is dangerous and non-standard behavior. This does not happen to xaml files, which is why I am assuming it is related to this plugin.

I am running Rider 2024.2.6 although this issue was also happening in 2024.2.5

**Steps to reproduce:**
1. Open an AXAML file that is longer than the editor panel so that a vertical scroll bar is present.
2. Make a change to the file.
3. Scroll until the change is out of view.
4. Undo the last change either via keyboard shortcut or menu.

**Comment by ForNeVeR** [comment]
Please try reproducing this without the plugin installed, and report to Rider if it still reproduces.

**Comment by grenaria** [comment]
I went to reproduce the issue and it's magically resolved. I'm not even mad.

**Comment by ForNeVeR** [comment]
Um well, alright.
