### ISSUE TITLE
Compiled Binding Path shows XAML error 

### ISSUE THREAD

**Issue by JaggerJo** [ForNeVeR/AvaloniaRider#463]
AvaloniaRider: 1.5.1.201

When Binding to the value of a nullable `struct` value (`Nullable<T>`) the XAML editor suggests invalid binding paths. The correct binding path is marked as an error.

Example:

```csharp
public struct Options
{
    public int MagicNumber { get; set; }
}

public class MainWindowViewModel
{
    // Options is nullable!
    public Options? Options { get; set; } = new Options();
}
```

What Rider suggests and thinks is valid (yield compiler error):
<img width="990" alt="image" src="https://github.com/user-attachments/assets/fc08553e-d0c0-4c96-95b4-5f0a49d2486c" />

What is correct, but Rider thinks is invalid (compiles fine):
<img width="990" alt="image" src="https://github.com/user-attachments/assets/2b0f9de4-f299-4186-8225-e4b210325c5a" />

## Sample

[Archive.zip](https://github.com/user-attachments/files/18111734/Archive.zip)

**Comment by ForNeVeR** [comment]
Please report to ReSharper. This plugin doesn't do any code highlighting, sorry.

**Comment by JaggerJo** [comment]
@ForNeVeR thanks for the hint 👍

Created an issue [here](https://youtrack.jetbrains.com/issue/RSRP-499602/Compiled-Binding-Path-shows-XAML-error).
