### ISSUE TITLE
No output in preview window on MacOS

### ISSUE THREAD

**Issue by hexdump2002** [ForNeVeR/AvaloniaRider#57]
After installing the plugin in rider through the Preferencers->Plugin panel and restart the IDE I see how when selecting a xaml file a panel appears to the right of the xml file but nothing is shown.

This is the plugin installed:
![imagen](https://user-images.githubusercontent.com/7756851/80576657-df0f1a80-8a05-11ea-9ff5-e53a8789409c.png)

And this the empty panel:

![imagen](https://user-images.githubusercontent.com/7756851/80576623-ce5ea480-8a05-11ea-89f6-f32d5a7dfc8a.png)

Is there anything I can do to fix this?

**Comment by ForNeVeR** [comment]
For the current preview build, you should open a plugin tool window (called just "Avalonia") and check for the designer process output:
![image](https://user-images.githubusercontent.com/92793/80726523-b20a5700-8b2e-11ea-89a2-ed67e4d97068.png)

Most likely, your project wasn't built yet, and designer didn't found the binaries to load the preview.
