### ISSUE TITLE
Black square shown for some frames

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#60]
Sometimes, when editing a simple XAML document, preview loads a black square instead of some frames. Closer inspection shows that it seemingly receives this black square from an Avalonia previewer process. Further investigation is required.

Also, check if the web previewer has the same problem.

**Comment by rstm-sf** [comment]
Hello, we can replace type `BufferedImage.TYPE_INT_RGB` with `BufferedImage.TYPE_INT_ARGB`?

https://github.com/ForNeVeR/AvaloniaRider/blob/b3fb65464f31221850ed875da10daf9501a4cd66/src/rider/main/kotlin/idea/editor/BitmapPreviewEditorComponent.kt#L43

It seems like the problem is this

**Comment by ForNeVeR** [comment]
Nope, it doesn't change anything. I still claim that the black squares come from the previewer process.

**Comment by ForNeVeR** [comment]
Reported to upstream as https://github.com/AvaloniaUI/Avalonia/issues/4264.
