### ISSUE TITLE
Preview of XAML code in Rider

### ISSUE THREAD

**Issue by GWawrzeniecki** [ForNeVeR/AvaloniaRider#67]
Hello
Is this possible to have a preview of XAML code in Rider from this plugin?
And if yes, how to to this?

**Comment by ForNeVeR** [comment]
Hello. Yes, it should be possible.

1. Open [the Actions page](https://github.com/ForNeVeR/AvaloniaRider/actions?query=workflow%3A%22Build+and+Test%22+branch%3Amaster+is%3Acompleted) (I've added a filter for `master` branch to this link)
2. Downloasd the latest plugin build (the artifact is named "distribution")
3. Unpack the `distribution` archive (you'll get a file named `avaloniarider-1.3.3.7.zip`)¹
4. Open Rider **Settings | Plugins**, press the gear icon and choose **Install from disk**
5. Navigate to `avaloniarider-1.3.3.7.zip` and choose it as the plugin distribution
6. Restart Rider
7. Open an Avalonia-based executable project (support for library projects [isn't here yet](https://github.com/ForNeVeR/AvaloniaRider/issues/55)), and then open any XAML file: the preview should open automatically

We're slowly moving towards [the 1.0 release](https://github.com/ForNeVeR/AvaloniaRider/milestone/1), after which the plugin will be available in Rider plugin repository.

Please let me know if you have any further questions.

¹ I believe this step could be removed if we tune our CI better, I'll file a separate issue about that.
