### ISSUE TITLE
Bad FPS for AvaloniaRemote previewer

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#70]
To test, add this style:
```xaml
<Window.Styles>
    <Style Selector="Canvas">
    <Style.Animations>
      <Animation Duration="0:0:1"
                     Easing="QuadraticEaseInOut"
                     IterationCount="Infinite">
            <KeyFrame Cue="50%">
              <Setter Property="ScaleTransform.ScaleX" Value="0.8"/>
              <Setter Property="ScaleTransform.ScaleY" Value="0.8"/>
              <Setter Property="RotateTransform.Angle" Value="150"/>
            </KeyFrame>
          </Animation>
     </Style.Animations>
  </Style>
</Window.Styles>
```

and apply to any XAML element.

While web previewer draws this animation nicely, AvaloniaRemote one gives about 5 FPS.

Probably caused by #40.

**Comment by wdcossey** [comment]
@ForNeVeR 

I haven't noticed any performance issues with the latest master branch, is this still an issue?

**Comment by wdcossey** [comment]
Managed to get more performance as per my https://github.com/ForNeVeR/AvaloniaRider/issues/83#issuecomment-703628326

https://github.com/wdcossey/AvaloniaRider/blob/6339f6e82df16b38c9620fa4b7efcca11bb70684/src/rider/main/kotlin/previewer/framebuffer/FrameBufferImage.kt
