### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/AvaloniaRider#9]
> _Note to myself_: raise an issue about hidpi support

_Originally posted by @ForNeVeR in https://github.com/ForNeVeR/AvaloniaRider/pull/7/files_

See this code:
https://github.com/ForNeVeR/AvaloniaRider/blob/2c1e8db8eb779e8d62373a0d21a7b43070418e9c/src/rider/main/kotlin/previewer/AvaloniaPreviewerSessionController.kt#L93

See also `// TODO[#9]: Update the image size for the renderer`

**Comment by MikeCodesDotNET** [comment]
I've had a play with resolving the DPI issue as its a blocker for me adopting Rider fulltime and found the following APIs. 

`        val screenDpi = Toolkit.getDefaultToolkit().screenResolution
`

You can also get the system scale with: 
`
val sysScale = JBUIScale.sysScale()
`

You'll need to import the following for these APIs to work:

```
import com.intellij.ui.scale.JBUIScale
import java.awt.*
```

This should give you everything you need, assuming the webview version doesn't already fix this.

**Comment by DmitriyYukhanov** [comment]
Hey,

Thanks for all your hard work implementing Avalonia support!
Would be great to fix the incorrect scaling when using non-100% UI scaling on Windows. 
Here is an example of how preview looks like when using 125% display scaling (Settings > Display > Scale and Layout set to 125%) with 2560 x 1440 resolution:

![image](https://user-images.githubusercontent.com/883587/163149710-22a3fe91-5ea3-4dee-847a-a80d51096702.png)
