### ISSUE TITLE
Need to build project to first start plugin.

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#90]
Till I don't run my proj plugin show nothing.
![image](https://user-images.githubusercontent.com/33497292/97081463-4c91b180-160b-11eb-84d0-486875b2239a.png)

**Comment by wdcossey** [comment]
This is to be expected, WPF works the same way, you can't preview anything until the project is built.

You don't need to `run` your project(s), you can simply build/rebuild them to enable/activate the preview.

**Comment by ForNeVeR** [comment]
While this is expected, we have to handle it somehow (e.g. offer the user a button to build the project, the same as Windows Forms previewer does).

**Comment by wdcossey** [comment]
The buttons/actions are already in the IDE, we can simply clone the action as is in the split previewer and/or display a message (in the preview) to inform the end-user to re/build the project.

**Comment by CreateLab** [comment]
As for me it's unexpectable. If I open a project, I wanna just see preview. ( and I have no information that I need to build project)

**Comment by andrfgs** [comment]
Still on the same subject as this issue/feature, is there any way to prevent the Avalonia log view from creating new tabs every time you build the project? It's not that really much of an issue but still.

**Comment by ForNeVeR** [comment]
@andrfgs, for better manageability, please create a new issue about that. It is unrelated to the current one.
