### ISSUE TITLE
Plugin lags behind reality

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#91]
``` 
<TextBlock Text="" HorizontalAlignment="Center" VerticalAlignment="Center"/>
```
Print some text in Text property. When delete all, plugin show last letter.
![image](https://user-images.githubusercontent.com/33497292/97081567-e0fc1400-160b-11eb-89c9-a9113a4c6eef.png)

**Comment by wdcossey** [comment]
Not entirely sure this is a bug with the AvaloniaRider previewer, I have noticed it before with the VS version too.

**Comment by ForNeVeR** [comment]
If so, then we should get a stable repro and report to Avalonia.

**Comment by wdcossey** [comment]
I will double check in VS this evening and see if it can be reproduced!

**Comment by ForNeVeR** [comment]
I wasn't able to reproduce this problem. Please drop a comment if you still reproduce it.
