### ISSUE TITLE
No preview in libs

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#93]
![image](https://user-images.githubusercontent.com/33497292/97797454-2b921780-1c2e-11eb-852f-534777f5f54d.png)

Can't see my window in plugin
https://github.com/AvaloniaUtils/MessageBox.Avalonia/blob/master/src/MessageBox.Avalonia/Views/MsBoxCustomWindow.xaml

**Comment by ForNeVeR** [comment]
Duplicate of #55.
