### ISSUE TITLE
Non-actual files are copied to the output folder

### ISSUE THREAD

**Issue by rstm-sf** [ForNeVeR/AvaloniaRider#94]
Hello!

Non-actual files are copied to the output folder. A file is copied before `compileKotlin`

We must either remove the lines associated with this folder from the script, or rewrite the script

https://github.com/ForNeVeR/AvaloniaRider/blob/13894ef760df09f5ce5b948318fa845155740d62/build.gradle#L88-L96

**Comment by ForNeVeR** [comment]
Sorry, which files are non-actual?

**Comment by rstm-sf** [comment]
If I build, then edit the kotlin files and build again, I get the following result

```
> ./gradlew buildPlugin
```

![image](https://user-images.githubusercontent.com/2669927/98468168-076ca280-21fb-11eb-95f3-64eca6593d03.png)

Although, with scharp files I get the same result

![image](https://user-images.githubusercontent.com/2669927/98468328-d04ac100-21fb-11eb-93a3-d3ce9e8a22dd.png)

**Comment by ForNeVeR** [comment]
I am sorry, it is still unclear what the problem is. Something doesn't work? If so, then what?

**Comment by rstm-sf** [comment]
If we build with grandle,
after that we edit the files,
then we build again,
then the changes are not present to the `output` folder

**Comment by ForNeVeR** [comment]
I am sorry, but I still don't understand your concern.

I have conducted the following experiment:
1. `./gradlew buildPlugin`
2. `cp .\build\distributions\avaloniarider-1.0.0.0.zip ./avaloniarider.old.zip`
3. Go to `RiderProjectOutputHost` and change it in some way you'll be able to detect (say, I've been changing first line of `GetProjectOutputModel` method to `throw new System.Exception();`
4. `./gradlew buildPlugin`
5. `cp .\build\distributions\avaloniarider-1.0.0.0.zip ./avaloniarider.new.zip`
6. Compare `./avaloniarider.old.zip` and `./avaloniarider.new.zip`

I've done all that, and got the results I was expecting: the binary inside of the archive was updated between these two files.

Do you observe any unexpected behavior? If so, could you please post the detailed steps for me to reproduce the issue?

**Comment by rstm-sf** [comment]
Because you are looking at the build  `distributions/folder`

I'm talking about `output` ;)
https://github.com/ForNeVeR/AvaloniaRider/blob/13894ef760df09f5ce5b948318fa845155740d62/build.gradle#L91-L93

**Comment by ForNeVeR** [comment]
Okay, why would you care about `output`?

**Comment by rstm-sf** [comment]
Because it is being created for some reason, the purpose of its creation and copying the old results there is not clear. I took the result from there several times and did not understand why nothing had changed

**Comment by ForNeVeR** [comment]
Thanks, this really seems like a problem (we never use that directory anyway). I'll drop it.
