### ISSUE TITLE
Unable to resolve type DesignInstance

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#95]
```
XamlParseException at 8:9: Unable to resolve type DesignInstance from namespace http://schemas.microsoft.com/expression/blend/2008 Line 8, position 9. XamlX.XamlParseException: Unable to resolve type DesignInstance from namespace http://schemas.microsoft.com/expression/blend/2008 Line 8, position 9. at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node) at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) at XamlX.Ast.XamlAstXamlPropertyValueNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict) at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlTypeBuilder`1 tb, IXamlType overrideRootType) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```

![image](https://user-images.githubusercontent.com/33497292/98602190-1f265280-22f1-11eb-9fff-f1caa1c12fc1.png)

https://github.com/CreateLab/NeBrowser/blob/master/Views/MainWindow.xaml
JetBrains Rider 2020.2.4
Build #RD-202.7660.16, built on September 30, 2020
Licensed to MessageBox for Avalonia UI 
Subscription is active until February 10, 2021
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core 3.1.6
Linux 5.4.0-52-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: com.intellij.javafx, avalonia-rider, com.microsoft.vso.idea
Current Desktop: KDE

**Comment by CreateLab** [comment]
![image](https://user-images.githubusercontent.com/33497292/98602330-572d9580-22f1-11eb-9d24-2434c7044885.png)

app works probably well

**Comment by CreateLab** [comment]
XamlParseException at 8:9: Unable to resolve type DesignInstance from namespace http://schemas.microsoft.com/expression/blend/2008 Line 8, position 9. XamlX.XamlParseException: Unable to resolve type DesignInstance from namespace http://schemas.microsoft.com/expression/blend/2008 Line 8, position 9. at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict) at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node) at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) at XamlX.Ast.XamlAstXamlPropertyValueNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor) at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor) at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor) at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict) at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlTypeBuilder`1 tb, IXamlType overrideRootType) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()

**Comment by ForNeVeR** [comment]
I can see you've reported that upstream. I believe, that, if it is an issue at all, it should be resolved in the Avalonia or XamlX repositories.

As a side note, I'm not sure this is an issue, and don't think that Avalonia should resolve this particular WPF construct.
